steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ollama-repo/ollama-phi3', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ollama-repo/ollama-phi3']
artifacts:
  images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ollama-repo/ollama-phi3'
